#ifndef __ILLTOOLSTRINGS_H__
#define __ILLTOOLSTRINGS_H__

//========================================================================================
//
//  IllTool — Localized UI Strings
//
//  Centralized NSLocalizedString macros for all panel controllers.
//  Prefix: kITS_ (IllTool Strings)
//
//  Tooltip strings are intentionally left as inline NSLocalizedString
//  in each panel (they are long and panel-specific).
//
//========================================================================================

// --- Common (shared across panels) ---
#define kITS_Apply              NSLocalizedString(@"Apply", @"Button: apply/commit changes")
#define kITS_CutOut             NSLocalizedString(@"Cut Out", @"Button: cut out subject (commit)")
#define kITS_Create             NSLocalizedString(@"Create", @"Button: create (normal reference, form edges)")
#define kITS_Trace              NSLocalizedString(@"Trace", @"Button: trace image to vectors")
#define kITS_Extract            NSLocalizedString(@"Extract", @"Button: extract form edges")
#define kITS_Correct            NSLocalizedString(@"Correct", @"Button: apply correction")
// kITS_Analyze is defined below in the non-Common section
#define kITS_Separate           NSLocalizedString(@"Separate", @"Button: separate into layers (depth)")
#define kITS_Segment            NSLocalizedString(@"Segment", @"Button: segment image")
#define kITS_Scan               NSLocalizedString(@"Scan", @"Button: scan contours")
#define kITS_Convert            NSLocalizedString(@"Convert", @"Button: convert contour to path")
#define kITS_Label              NSLocalizedString(@"Label", @"Button: label contours")
#define kITS_Nest               NSLocalizedString(@"Nest", @"Button: nest contours")
#define kITS_Detect             NSLocalizedString(@"Detect", @"Button: detect pose keypoints")
#define kITS_Clean              NSLocalizedString(@"Clean", @"Button: clean up selected shapes")
#define kITS_Transform          NSLocalizedString(@"Transform", @"Button: apply transform")
#define kITS_Cancel             NSLocalizedString(@"Cancel", @"Button: cancel operation")
#define kITS_Preview            NSLocalizedString(@"Preview", @"Button: generate preview")
#define kITS_Clear              NSLocalizedString(@"Clear", @"Button: clear/reset")
#define kITS_ClearPreview       NSLocalizedString(@"Clear Preview", @"Button: clear preview overlay")
#define kITS_Run                NSLocalizedString(@"Run", @"Button: execute operation")
#define kITS_Save               NSLocalizedString(@"Save", @"Button: save preset")
#define kITS_Load               NSLocalizedString(@"Load", @"Button: load preset")
#define kITS_Reset              NSLocalizedString(@"Reset", @"Button: reset to defaults")
#define kITS_Confirm            NSLocalizedString(@"Confirm", @"Button: confirm operation")
#define kITS_Undo               NSLocalizedString(@"Undo", @"Button: undo last operation")
#define kITS_Merge              NSLocalizedString(@"Merge", @"Button: merge items")
#define kITS_Finalize           NSLocalizedString(@"Finalize", @"Button: finalize current path")
#define kITS_Simplification     NSLocalizedString(@"Simplification", @"Slider: path simplification")
#define kITS_Sensitivity        NSLocalizedString(@"Sensitivity:", @"Label: sensitivity slider")

// --- Selection Panel ---
#define kITS_SelectionTools     NSLocalizedString(@"Selection Tools", @"Title: selection panel")
#define kITS_Lasso              NSLocalizedString(@"Lasso", @"Segment: lasso selection mode")
#define kITS_Smart              NSLocalizedString(@"Smart", @"Segment: smart selection mode")
#define kITS_LassoHelp          NSLocalizedString(@"Click to place points, Enter or double-click to select", @"Status: lasso mode instructions")
#define kITS_SmartHelp          NSLocalizedString(@"Click a path to select related", @"Status: smart mode instructions")
#define kITS_AddToSelection     NSLocalizedString(@"Add to Selection", @"Checkbox: add to selection")
#define kITS_AnchorsSelected    NSLocalizedString(@"%d anchors selected", @"Status: selection count")
#define kITS_SimilarityThresh   NSLocalizedString(@"Similarity Threshold", @"Label: smart select threshold")

// --- Cleanup Panel ---
#define kITS_ShapeCleanup       NSLocalizedString(@"Shape Cleanup", @"Title: shape cleanup tab")
#define kITS_Shape              NSLocalizedString(@"Shape", @"Tab: shape classification tab")
#define kITS_Decompose          NSLocalizedString(@"Decompose", @"Tab: auto-decompose tab")
#define kITS_Detected           NSLocalizedString(@"Detected:", @"Label: detected shape type")
#define kITS_CurveTension       NSLocalizedString(@"Curve Tension", @"Slider: curve tension")
#define kITS_PointsN            NSLocalizedString(@"Points: %d", @"Label: anchor point count")
#define kITS_PointsNLong        NSLocalizedString(@"Points: %ld", @"Label: anchor point count (long)")
#define kITS_LayerName          NSLocalizedString(@"Layer Name", @"Label: layer name field")
#define kITS_LayerNamePlaceholder NSLocalizedString(@"Layer name...", @"Placeholder: layer name input")
#define kITS_AverageSelection   NSLocalizedString(@"Average Selection", @"Button: average selection")
#define kITS_DeleteOriginals    NSLocalizedString(@"Delete Originals", @"Checkbox: delete originals")
#define kITS_SelectSmall        NSLocalizedString(@"Select Small", @"Button: select small objects")
#define kITS_MaxPts             NSLocalizedString(@"Max Pts", @"Label: max points threshold")
#define kITS_AutoDecompose      NSLocalizedString(@"Auto-Decompose", @"Title: decompose section")
#define kITS_Analyze            NSLocalizedString(@"Analyze", @"Button: analyze/scan")
#define kITS_Clusters           NSLocalizedString(@"Clusters:", @"Label: cluster count")
#define kITS_AcceptAll          NSLocalizedString(@"Accept All", @"Button: accept all results")
#define kITS_Split              NSLocalizedString(@"Split", @"Button: split cluster")
#define kITS_MergeGroups        NSLocalizedString(@"Merge Groups", @"Button: merge groups")

// --- Grouping Panel ---
#define kITS_GroupingTools      NSLocalizedString(@"Grouping Tools", @"Title: grouping panel")
#define kITS_GroupName          NSLocalizedString(@"Group Name", @"Label: group name field")
#define kITS_GroupNamePlaceholder NSLocalizedString(@"Enter group name...", @"Placeholder: group name")
#define kITS_CopyToGroup        NSLocalizedString(@"Copy to Group", @"Button: copy to group")
#define kITS_UntitledGroup      NSLocalizedString(@"Untitled Group", @"Default: unnamed group")
#define kITS_DetachFromGroup    NSLocalizedString(@"Detach from Group", @"Button: detach from group")
#define kITS_SplitToNewGroup    NSLocalizedString(@"Split to New Group", @"Button: split to new group")

// --- Shading Panel ---
#define kITS_Shading            NSLocalizedString(@"Shading", @"Title: shading panel")
#define kITS_Blend              NSLocalizedString(@"Blend", @"Segment/Title: blend mode/panel")
#define kITS_Mesh               NSLocalizedString(@"Mesh", @"Segment: mesh mode")
#define kITS_Highlight          NSLocalizedString(@"Highlight:", @"Label: highlight color")
#define kITS_Shadow             NSLocalizedString(@"Shadow:", @"Label: shadow color")
#define kITS_Pick               NSLocalizedString(@"Pick", @"Button: eyedropper pick color")
#define kITS_LightDirection     NSLocalizedString(@"Light Direction", @"Label: light direction widget")
#define kITS_Intensity          NSLocalizedString(@"Intensity", @"Slider: intensity")
#define kITS_Steps              NSLocalizedString(@"Steps", @"Slider: blend steps count")
#define kITS_Grid               NSLocalizedString(@"Grid", @"Label/Tab: grid")
#define kITS_ApplyShading       NSLocalizedString(@"Apply Shading", @"Button: apply shading")

// --- Blend Panel ---
#define kITS_PickA              NSLocalizedString(@"Pick A", @"Button: pick blend path A")
#define kITS_PickB              NSLocalizedString(@"Pick B", @"Button: pick blend path B")
#define kITS_NoPathsSelected    NSLocalizedString(@"No paths selected", @"Status: no blend paths")
#define kITS_ReadyToBlend       NSLocalizedString(@"Ready to blend", @"Status: both paths set")
#define kITS_PathASet           NSLocalizedString(@"Path A set", @"Status: path A selected")
#define kITS_PathBSet           NSLocalizedString(@"Path B set", @"Status: path B selected")
#define kITS_Easing             NSLocalizedString(@"Easing", @"Label: easing presets")
#define kITS_EasingLin          NSLocalizedString(@"Lin", @"Button: linear easing")
#define kITS_EasingIn           NSLocalizedString(@"In", @"Button: ease in")
#define kITS_EasingOut          NSLocalizedString(@"Out", @"Button: ease out")
#define kITS_EasingInOut        NSLocalizedString(@"InOut", @"Button: ease in-out")

// --- Perspective Panel ---
#define kITS_SetPerspective     NSLocalizedString(@"Set Perspective", @"Button: set perspective grid")
#define kITS_ResetPerspective   NSLocalizedString(@"Reset Perspective", @"Button: reset perspective grid")
#define kITS_AddVertical        NSLocalizedString(@"Add Vertical", @"Button: add vertical VP")
#define kITS_AutoMatch          NSLocalizedString(@"Auto Match", @"Button: auto-match perspective")
#define kITS_Lock               NSLocalizedString(@"Lock", @"Checkbox: lock grid")
#define kITS_Show               NSLocalizedString(@"Show", @"Checkbox: show grid")
#define kITS_DeleteGrid         NSLocalizedString(@"Delete Grid", @"Button: delete perspective grid")
#define kITS_SnapToPersp        NSLocalizedString(@"Snap to Perspective", @"Checkbox: snap to grid")
#define kITS_AdaptiveCanny      NSLocalizedString(@"Adaptive Canny", @"Checkbox: adaptive edge detection")
#define kITS_3PointPerspective  NSLocalizedString(@"3-Point Perspective", @"Checkbox: enable 3-point VP")
#define kITS_ShowVPLines        NSLocalizedString(@"Show VP Lines", @"Checkbox: show detected VP lines")
#define kITS_LineColors         NSLocalizedString(@"Line Colors:", @"Label: VP color legend")
#define kITS_NoGrid             NSLocalizedString(@"No grid", @"Status: no perspective grid")
#define kITS_TwoPointPersp      NSLocalizedString(@"2-point perspective", @"Status: 2-point grid")
#define kITS_ThreePointPersp    NSLocalizedString(@"3-point perspective", @"Status: 3-point grid")
#define kITS_LockedTwoPoint     NSLocalizedString(@"Locked \u2014 2-point", @"Status: locked 2-point")
#define kITS_LockedThreePoint   NSLocalizedString(@"Locked \u2014 3-point", @"Status: locked 3-point")
#define kITS_LinesPlaced        NSLocalizedString(@"%d line(s) placed", @"Status: placed line count")
#define kITS_VPNotSet           NSLocalizedString(@"%@ \u2014 Not set", @"Label: VP not placed")
#define kITS_Horizon            NSLocalizedString(@"Horizon", @"Slider: horizon position")
#define kITS_GridDensity        NSLocalizedString(@"Grid Density", @"Slider: grid density")
#define kITS_Preset             NSLocalizedString(@"Preset", @"Label: preset section")
#define kITS_SavePreset         NSLocalizedString(@"Save Preset", @"Button: save preset")
#define kITS_LoadPreset         NSLocalizedString(@"Load Preset", @"Button: load preset")
#define kITS_ClearGrid          NSLocalizedString(@"Clear Grid", @"Button: clear grid lines")
#define kITS_Mirror             NSLocalizedString(@"Mirror", @"Tab/Button: mirror operation")
#define kITS_Duplicate          NSLocalizedString(@"Duplicate", @"Tab/Button: duplicate operation")
#define kITS_Paste              NSLocalizedString(@"Paste", @"Tab: paste in perspective")
#define kITS_Axis               NSLocalizedString(@"Axis:", @"Label: mirror axis")
#define kITS_Vertical           NSLocalizedString(@"Vertical", @"Segment: vertical axis")
#define kITS_Horizontal         NSLocalizedString(@"Horizontal", @"Segment: horizontal axis")
#define kITS_Custom             NSLocalizedString(@"Custom", @"Segment: custom setting")
#define kITS_ReplaceOriginal    NSLocalizedString(@"Replace original (copy by default)", @"Checkbox: replace original")
#define kITS_Count              NSLocalizedString(@"Count:", @"Label: duplicate count")
#define kITS_Spacing            NSLocalizedString(@"Spacing:", @"Label: spacing mode")
#define kITS_EqualPersp         NSLocalizedString(@"Equal in Perspective", @"Popup: perspective spacing")
#define kITS_EqualScreen        NSLocalizedString(@"Equal in Screen", @"Popup: screen spacing")
#define kITS_Plane              NSLocalizedString(@"Plane:", @"Label: paste plane")
#define kITS_Floor              NSLocalizedString(@"Floor", @"Segment: floor plane")
#define kITS_LeftWall           NSLocalizedString(@"Left Wall", @"Segment: left wall plane")
#define kITS_RightWall          NSLocalizedString(@"Right Wall", @"Segment: right wall plane")
#define kITS_Scale              NSLocalizedString(@"Scale:", @"Label: paste scale")
#define kITS_PasteInPersp       NSLocalizedString(@"Paste in Perspective", @"Button: paste in perspective")

// --- Transform Panel ---
#define kITS_TransformAll       NSLocalizedString(@"Transform All", @"Title: transform panel")
#define kITS_Mode               NSLocalizedString(@"Mode", @"Label: transform mode")
#define kITS_Absolute           NSLocalizedString(@"Absolute", @"Segment: absolute mode")
#define kITS_Relative           NSLocalizedString(@"Relative", @"Segment: relative mode")
#define kITS_Width              NSLocalizedString(@"Width:", @"Label: width field")
#define kITS_Height             NSLocalizedString(@"Height:", @"Label: height field")
#define kITS_Rotation           NSLocalizedString(@"Rotation:", @"Label: rotation field")
#define kITS_RandomVariance     NSLocalizedString(@"Random (\u00B120% variance)", @"Checkbox: random variance")
#define kITS_LockAspectRatio    NSLocalizedString(@"Lock Aspect Ratio", @"Checkbox: lock aspect ratio")
#define kITS_SelectedAnchors    NSLocalizedString(@"Selected: %ld anchor%s", @"Label: selected anchor count")

// --- Merge Panel ---
#define kITS_SmartMerge         NSLocalizedString(@"Smart Merge", @"Title: merge panel")
#define kITS_Tolerance          NSLocalizedString(@"Tolerance", @"Slider: merge tolerance")
#define kITS_TolerancePt        NSLocalizedString(@"%d pt", @"Label: tolerance value in points")
#define kITS_ScanEndpoints      NSLocalizedString(@"Scan Endpoints", @"Button: scan endpoints")
#define kITS_PairsFound         NSLocalizedString(@"0 pairs found, 0 paths", @"Label: scan results default")
#define kITS_ChainMerge         NSLocalizedString(@"Chain Merge", @"Checkbox: chain merge mode")
#define kITS_PreserveHandles    NSLocalizedString(@"Preserve Handles", @"Checkbox: preserve handles")

// --- Pen Panel ---
#define kITS_IllPen             NSLocalizedString(@"Ill Pen", @"Title: pen tool panel")
#define kITS_PenModeActive      NSLocalizedString(@"Pen Mode Active", @"Checkbox: pen mode toggle")
#define kITS_PathName           NSLocalizedString(@"Path Name:", @"Label: path name field")
#define kITS_TargetGroup        NSLocalizedString(@"Target Group:", @"Label: target group field")
#define kITS_None               NSLocalizedString(@"None", @"Popup: no group")
#define kITS_Chamfer            NSLocalizedString(@"Chamfer", @"Section: chamfer settings")
#define kITS_Radius             NSLocalizedString(@"Radius:", @"Label: chamfer radius")
#define kITS_UniformEdges       NSLocalizedString(@"Uniform Edges", @"Checkbox: uniform edges")
#define kITS_PresetLabel        NSLocalizedString(@"Preset:", @"Label: preset popup")
#define kITS_PresetSharp        NSLocalizedString(@"Sharp", @"Preset: sharp corners")
#define kITS_PresetSoft         NSLocalizedString(@"Soft", @"Preset: soft corners")
#define kITS_PresetRound        NSLocalizedString(@"Round", @"Preset: round corners")
#define kITS_PresetCustom       NSLocalizedString(@"Custom", @"Preset: custom corners")
#define kITS_ClickDrawHelp      NSLocalizedString(@"Click to draw, double-click to finish", @"Status: pen drawing instructions")
#define kITS_EnablePenHelp      NSLocalizedString(@"Enable Pen Mode to draw", @"Status: pen mode inactive")

// --- Surface Panel ---
#define kITS_SurfaceExtraction  NSLocalizedString(@"Surface Extraction", @"Title: surface panel")
#define kITS_ClickToExtract     NSLocalizedString(@"Click-to-Extract Mode", @"Checkbox: extract mode")
#define kITS_SurfaceDefault     NSLocalizedString(@"Surface: ---", @"Label: no surface detected")
#define kITS_SurfaceExtractHelp NSLocalizedString(@"Enable extract mode, then click on reference", @"Status: surface instructions")

// --- Trace Panel ---
#define kITS_IllTrace           NSLocalizedString(@"Ill Trace", @"Title: trace panel")
#define kITS_Outline            NSLocalizedString(@"Outline", @"Segment: outline output mode")
#define kITS_Fill               NSLocalizedString(@"Fill", @"Segment: fill output mode")
#define kITS_Centerline         NSLocalizedString(@"Centerline", @"Segment: centerline output mode")
#define kITS_Image              NSLocalizedString(@"Image", @"Tab: image operations")
#define kITS_Vectors            NSLocalizedString(@"Vectors", @"Tab: vector operations")
#define kITS_TraceDefaultHelp   NSLocalizedString(@"Expand a section, adjust params, click Run", @"Status: trace default instructions")
#define kITS_PreviewPreprocess  NSLocalizedString(@"Preview Preprocessing", @"Button: preview preprocessing")
#define kITS_CenterlineSettings NSLocalizedString(@"Centerline Settings", @"Label: centerline section header")
#define kITS_Smoothness         NSLocalizedString(@"Smoothness", @"Label: smoothness slider")
#define kITS_ClickThreshold     NSLocalizedString(@"Click Threshold", @"Label: click threshold")
#define kITS_SubjectCutout      NSLocalizedString(@"Subject Cutout", @"Section: subject cutout")
#define kITS_ExtractingSubject  NSLocalizedString(@"Extracting subject...", @"Status: extracting")
#define kITS_NoPreviewToCommit  NSLocalizedString(@"No preview to commit \u2014 click Preview first", @"Status: no preview")
#define kITS_CreatingCutPaths   NSLocalizedString(@"Creating cut paths...", @"Status: creating paths")
#define kITS_RecompositingInst  NSLocalizedString(@"Recompositing instances...", @"Status: recompositing")
#define kITS_DarkOnLight        NSLocalizedString(@"Dark on Light", @"Checkbox: dark on light contours")
#define kITS_IncludeFace        NSLocalizedString(@"Include Face Landmarks", @"Checkbox: face landmarks")
#define kITS_IncludeHands       NSLocalizedString(@"Include Hand Pose", @"Checkbox: hand pose")
#define kITS_LayerCount         NSLocalizedString(@"Layer Count", @"Label: depth layer count")
#define kITS_ShowMidline        NSLocalizedString(@"Show Midline", @"Checkbox: symmetry midline")
#define kITS_GoodSide           NSLocalizedString(@"Good Side", @"Label: symmetry good side")
#define kITS_Left               NSLocalizedString(@"Left", @"Segment: left side")
#define kITS_Right              NSLocalizedString(@"Right", @"Segment: right side")
#define kITS_BlendLabel         NSLocalizedString(@"Blend", @"Label: blend width slider")

// --- Layer Panel ---
#define kITS_IllLayers          NSLocalizedString(@"Ill Layers", @"Title: layers panel")
#define kITS_NoPreset           NSLocalizedString(@"No Preset", @"Popup: no preset selected")
#define kITS_SavePresetDots     NSLocalizedString(@"Save Preset...", @"Popup: save preset option")
#define kITS_Organize           NSLocalizedString(@"Organize", @"Button: auto-organize layers")
#define kITS_SaveLayerPreset    NSLocalizedString(@"Save Layer Preset", @"Alert: save preset title")
#define kITS_EnterPresetName    NSLocalizedString(@"Enter preset name:", @"Alert: preset name prompt")
#define kITS_MyPreset           NSLocalizedString(@"My Preset", @"Default: preset name")
#define kITS_NewLayer           NSLocalizedString(@"New Layer", @"Default: new layer name")
#define kITS_Group              NSLocalizedString(@"Group", @"Default: group name")
#define kITS_LayerCountFmt      NSLocalizedString(@"%d layers, %d objects", @"Status: layer/object count")

// --- Slider parameter labels used in Trace panel ---
// (These are short UI labels passed to addSliderRow: — localize them)
#define kITS_SpeckleFilter      NSLocalizedString(@"Speckle Filter:", @"Slider: vtracer speckle filter")
#define kITS_ColorPrecision     NSLocalizedString(@"Color Precision:", @"Slider: vtracer color precision")
#define kITS_CornerThreshold    NSLocalizedString(@"Corner Threshold:", @"Slider: vtracer corner threshold")
#define kITS_LengthThreshold    NSLocalizedString(@"Length Threshold:", @"Slider: vtracer length threshold")
#define kITS_SpliceAngle        NSLocalizedString(@"Splice Angle:", @"Slider: vtracer splice angle")
#define kITS_CurveFitIter       NSLocalizedString(@"Curve Fit Iterations:", @"Slider: vtracer curve fit iterations")
#define kITS_LayerDifference    NSLocalizedString(@"Layer Difference:", @"Slider: vtracer layer difference")
#define kITS_ModeLabel          NSLocalizedString(@"Mode:", @"Label: vtracer mode popup")
#define kITS_CannyLow           NSLocalizedString(@"Canny Low:", @"Slider: canny low threshold")
#define kITS_CannyHigh          NSLocalizedString(@"Canny High:", @"Slider: canny high threshold")
#define kITS_EdgeDilation       NSLocalizedString(@"Edge Dilation:", @"Slider: edge dilation radius")
#define kITS_SkeletonThreshold  NSLocalizedString(@"Skeleton Threshold:", @"Slider: skeleton threshold")
#define kITS_NormalStrength     NSLocalizedString(@"Normal Strength:", @"Slider: normal strength")
#define kITS_Threshold          NSLocalizedString(@"Threshold:", @"Slider: threshold value")
#define kITS_MinArea            NSLocalizedString(@"Min Area:", @"Slider: minimum area")
#define kITS_Iterations         NSLocalizedString(@"Iterations:", @"Slider: iteration count")
#define kITS_LearningRate       NSLocalizedString(@"Learning Rate:", @"Slider: learning rate")
#define kITS_Confidence         NSLocalizedString(@"Confidence:", @"Slider: confidence threshold")
#define kITS_KPlanes            NSLocalizedString(@"K Planes:", @"Slider: normal ref K planes")
#define kITS_PreBlurSigma       NSLocalizedString(@"Pre-Blur Sigma:", @"Slider: pre-blur sigma")
#define kITS_ClusteringStride   NSLocalizedString(@"Clustering Stride:", @"Slider: clustering stride")
#define kITS_ClusteringIter     NSLocalizedString(@"Clustering Iterations:", @"Slider: clustering iterations")
#define kITS_NumThresholds      NSLocalizedString(@"Num Thresholds:", @"Slider: number of thresholds")
#define kITS_BlurSigma          NSLocalizedString(@"Blur Sigma:", @"Slider: blur sigma")
#define kITS_StepSize           NSLocalizedString(@"Step Size:", @"Slider: scan step size")
#define kITS_ColorThreshold     NSLocalizedString(@"Color Threshold:", @"Slider: color threshold")
#define kITS_ToleranceLabel     NSLocalizedString(@"Tolerance:", @"Slider: path tolerance")
#define kITS_Depth              NSLocalizedString(@"Depth:", @"Slider: nesting depth")
#define kITS_Contrast           NSLocalizedString(@"Contrast", @"Slider: contour contrast")
#define kITS_Pivot              NSLocalizedString(@"Pivot", @"Slider: contour pivot")
#define kITS_SensitivityLabel   NSLocalizedString(@"Sensitivity:", @"Label: sensitivity")

#endif /* __ILLTOOLSTRINGS_H__ */
