"""Tests for character/model sheet generation.

Verifies 4 views generated, layout fits page, and proportion guides
at landmark heights.
All tests are pure Python — no JSX or Adobe required.
"""

import pytest

from adobe_mcp.apps.illustrator.character.character_sheet_gen import (
    generate_sheet_spec,
    sheet_layout,
    DEFAULT_LANDMARKS,
)


# ---------------------------------------------------------------------------
# 4 views generated by default
# ---------------------------------------------------------------------------


def test_four_views_generated():
    """Default sheet spec produces 4 turnaround views."""
    rig = {"character_name": "hero"}
    spec = generate_sheet_spec(rig)

    assert spec["view_count"] == 4
    assert len(spec["views"]) == 4

    # Default angles: front (0), 3/4 (30), side (90), back (180)
    angles = [v["angle"] for v in spec["views"]]
    assert angles == [0, 30, 90, 180]


# ---------------------------------------------------------------------------
# Layout fits page
# ---------------------------------------------------------------------------


def test_layout_fits_page():
    """All view rects fit within the page dimensions."""
    page_w, page_h = 2400, 1800
    layout = sheet_layout(4, (page_w, page_h), character_height=600)

    for rect in layout["view_rects"]:
        assert rect["x"] >= 0, f"View x={rect['x']} is negative"
        assert rect["y"] >= 0, f"View y={rect['y']} is negative"
        assert rect["x"] + rect["width"] <= page_w, (
            f"View right edge {rect['x'] + rect['width']} exceeds page width {page_w}"
        )
        assert rect["y"] + rect["height"] <= page_h, (
            f"View bottom {rect['y'] + rect['height']} exceeds page height {page_h}"
        )


# ---------------------------------------------------------------------------
# Proportion guides at landmark heights
# ---------------------------------------------------------------------------


def test_proportion_guides_at_landmarks():
    """Proportion guides are generated at each default landmark fraction."""
    rig = {"character_name": "hero"}
    spec = generate_sheet_spec(rig, character_height=600)

    guides = spec["guides"]

    # Should have one guide per default landmark
    assert len(guides) == len(DEFAULT_LANDMARKS)

    # Each guide should have a name and a y position
    guide_names = {g["name"] for g in guides}
    for landmark_name in DEFAULT_LANDMARKS:
        assert landmark_name in guide_names, f"Missing guide for '{landmark_name}'"

    # Guides should be sorted by fraction (top to bottom)
    fractions = [g["fraction"] for g in guides]
    assert fractions == sorted(fractions), "Guides should be sorted by fraction"
